CREATE TABLE "HR"."COMMENT" 
(	"COMMENT_NO" NUMBER(38,0), 
	"WRITER" VARCHAR2(100), 
	"POST_NO" NUMBER(38,0), 
	"CONTENT" VARCHAR2(100), 
	 CONSTRAINT "COMMENT_PK" PRIMARY KEY ("COMMENT_NO")
)

CREATE TABLE "HR"."MEMBERS" 
(	"ID" VARCHAR2(100), 
	"PW" VARCHAR2(100), 
	"NAME" VARCHAR2(100), 
	"AGE" NUMBER(38,0), 
	"MEM_ADDR" VARCHAR2(100), 
	 CONSTRAINT "MEMBERS_PK" PRIMARY KEY ("ID")
)

CREATE TABLE "HR"."PLACE" 
(	"PLACE_CODE" VARCHAR2(100), 
	"PLACE_NAME" VARCHAR2(100), 
	"PLACE_LOCATION" VARCHAR2(100), 
	"PLACE_GRADE" FLOAT(10), 
	"PLACE_CATEGORY" VARCHAR2(100), 
)

CREATE TABLE "HR"."POST" 
(	"POST_NO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"SCORE" NUMBER(38,0), 
	"WRITE_DATE" DATE, 
	"POST_CATEGORY" VARCHAR2(100), 
	 PRIMARY KEY ("POST_NO")
)

CREATE TABLE "HR"."RESERVATION" 
(	"R_NUM" NUMBER(38,0), 
	"R_ID" VARCHAR2(100), 
	"R_PEOPEL" VARCHAR2(100), 
	"R_PLACE" VARCHAR2(100), 
	"R_TIME" VARCHAR2(100), 
	 CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("R_NUM")
)