CREATE TABLE dept_temp2
AS SELECT * FROM DEPT

SELECT * FROM DEPT

SELECT * FROM dept_temp2

UPDATE dept_temp2
SET LOC = 'SEOUL'

SELECT * FROM dept_temp2

UPDATE dept_temp2
SET DNAME = 'DATABASE', LOC = 'BUSAN'
WHERE DEPTNO = 40

DELETE FROM DEPT_TEMP2
WHERE DNAME = 'SALES'

SELECT * FROM DEPT_TEMP2 dt

DROP TABLE dept_temp2

SELECT * FROM DEPT_TEMP2

CREATE TABLE dept_temp2
AS SELECT * FROM DEPT

SELECT * FROM DEPT

SELECT * FROM dept_temp2
