CREATE TABLE DEPT
(	DEPTNO NUMBER(2),
	DNAME VARCHAR2(14 BYTE),
	LOC VARCHAR2(13 BYTE)
)

CREATE TABLE EMP
(	EMPNO NUMBER(4),
	ENAME VARCHAR2(10 BYTE),
	JOB VARCHAR2(9 BYTE),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7,2),
	COMM NUMBER(7,2),
	DEPTNO NUMBER(2)
)

CREATE TABLE SALGRADE
(	GRADE NUMBER,
	LOSAL NUMBER,
	HISAL NUMBER
)

ALTER TABLE DEPT ADD (
CONSTRAINT PK_DEPT
PRIMARY KEY(DEPTNO));

ALTER TABLE EMP ADD (
CONSTRAINT PK_EMP
PRIMARY KEY(EMPNO));

ALTER TABLE EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES DEPT (DEPTNO));

-- selection
SELECT * FROM EMP

-- projection
SELECT deptno FROM EMP

-- distinct
SELECT DISTINCT deptno FROM EMP

SELECT ename, sal * 12 AS yearsal FROM EMP

SELECT * FROM EMP
ORDER BY sal DESC

SELECT * FROM EMP
WHERE DEPTNO = 30
ORDER BY EMPNO DESC

SELECT * FROM EMP
WHERE NOT DEPTNO = 30
ORDER BY EMPNO DESC

SELECT * FROM EMP
WHERE DEPTNO = 30 AND job = 'SALESMAN'

SELECT * FROM EMP
WHERE DEPTNO = 30 OR job = 'salesman'

SELECT * FROM EMP
WHERE sal >= 3000

SELECT * FROM EMP
WHERE sal != 3000

SELECT * FROM EMP
WHERE job IN ('SALESMAN', 'MANAGER')

SELECT * FROM EMP
WHERE job NOT IN ('SALESMAN', 'MANAGER')
ORDER BY job

SELECT * FROM EMP
WHERE sal BETWEEN 2000 AND 3000
ORDER BY EMPNO

SELECT * FROM EMP
WHERE sal NOT BETWEEN 2000 AND 3000
ORDER BY EMPNO

SELECT * FROM EMP
WHERE ename LIKE '_L%'

SELECT * FROM EMP
WHERE ename NOT LIKE '_L%'

SELECT * FROM EMP
WHERE comm IS NULL

SELECT * FROM EMP
WHERE comm IS NOT null